### ISSUE TITLE
APK crashed

### ISSUE THREAD

**Issue by 3togo** [JackyAndroid/AndroidTVLauncher#38]
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jacky.launcher/com.jacky.launcher.main.MainActivity}: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class fragment
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2756)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4652)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6388)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
Caused by: android.view.InflateException: Binary XML file line #6: Binary XML file line #6: Error inflating class fragment
Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class fragment
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v17.leanback.widget.PresenterSelector android.support.v17.leanback.widget.ObjectAdapter.getPresenterSelector()' on a null object reference
	at android.support.v17.leanback.app.ListRowDataAdapter.<init>(ListRowDataAdapter.java:30)
	at android.support.v17.leanback.app.BrowseFragment.setupMainFragment(BrowseFragment.java:1188)
	at android.support.v17.leanback.app.BrowseFragment.onCreateView(BrowseFragment.java:1158)
	at android.app.Fragment.performCreateView(Fragment.java:2353)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:959)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1149)
	at android.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2339)
	at android.app.FragmentController.onCreateView(FragmentController.java:98)
	at android.app.Activity.onCreateView(Activity.java:6071)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:802)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:752)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:883)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:846)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:522)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:430)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:377)
	at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:412)
	at android.app.Activity.setContentView(Activity.java:2492)
	at com.jacky.launcher.main.MainActivity.onCreate(MainActivity.java:50)
	at android.app.Activity.performCreate(Activity.java:6854)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2709)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2817)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4652)
	at android.app.ActivityThread.-wrap19(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1564)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6388)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:930)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)

**Comment by JackyAndroid** [comment]
Are you upgrade the gradle or v7 version?
